# Generated by Django 4.2.11 on 2024-05-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_initiale', models.DateField(blank=True)),
                ('date_finale', models.DateField(blank=True)),
                ('actuel', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Anneescolaire',
                'verbose_name_plural': 'Anneescolaire',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ecole', models.CharField(choices=[('MATERNELLE', 'MATERNELLE'), ('PRIMAIRE', 'PRIMAIRE')], default='', max_length=14)),
                ('nom', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=34)),
                ('prenom', models.CharField(max_length=34)),
                ('date_enquete', models.DateTimeField(blank=True)),
                ('condition_eleve', models.CharField(choices=[('CONF', 'CONF'), ('ABAN', 'ABAN'), ('PROP', 'PROP')], max_length=4)),
                ('sex', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('cs_py', models.CharField(choices=[('CS', 'CS'), ('Extra', 'EXTRA'), ('PY', 'PY')], max_length=6)),
                ('hand', models.CharField(choices=[('DA', 'DA'), ('DM', 'DM'), ('DL', 'DL'), ('DV', 'DV')], default='', max_length=2)),
                ('annee_inscr', models.CharField(max_length=4)),
                ('parent', models.CharField(max_length=34)),
                ('tel_parent', models.CharField(max_length=24)),
                ('note_eleve', models.CharField(blank=True, default='', max_length=240)),
                ('classe_nass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scuelo.classe')),
            ],
            options={
                'verbose_name': 'Eleve',
                'verbose_name_plural': 'Eleves',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causal', models.CharField(choices=[('insc', 'inscription'), ('sco', 'scolarite'), ('ten', 'tenue'), ('can', 'cantine')], max_length=34)),
                ('montant', models.PositiveBigIntegerField()),
                ('date_paiement', models.DateTimeField()),
                ('note_paiement', models.CharField(blank=True, max_length=200)),
                ('eleve_payment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scuelo.eleve')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scuelo.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scuelo.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scuelo.eleve')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
            },
        ),
    ]
