# Generated by Django 4.2.11 on 2024-05-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(default='', max_length=23),
        ),
    ]
