# Generated by Django 5.0.4 on 2024-05-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scuelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneescolaire',
            name='nom_bref',
            field=models.CharField(default='sdfds', max_length=10),
            preserve_default=False,
        ),
    ]
