# Generated by Django 5.0.6 on 2024-05-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='parent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='tel_parent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
