# Generated by Django 5.0.4 on 2024-04-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anneescolaire',
            options={'verbose_name': 'Anneescolaire', 'verbose_name_plural': 'Anneescolaire'},
        ),
        migrations.AlterModelOptions(
            name='inscription',
            options={'verbose_name': 'Inscription', 'verbose_name_plural': 'Inscriptions'},
        ),
    ]
