# Generated by Django 5.0.6 on 2024-05-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date_paye'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AddField(
            model_name='anneescolaire',
            name='nom_bref',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='causal',
            field=models.CharField(choices=[('INS', 'Inscription'), ('SCO', 'Scolarite'), ('TEN', 'Tenue'), ('CAN', 'Cantine')], db_index=True, max_length=5),
        ),
    ]
