# Generated by Django 4.2.11 on 2024-05-01 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0002_alter_anneescolaire_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causal', models.CharField(choices=[('insc', 'inscription'), ('sco', 'scolarite'), ('ten', 'tenue'), ('can', 'cantine')], max_length=34)),
                ('montant', models.PositiveBigIntegerField()),
                ('date_paiement', models.DateTimeField()),
                ('note_paiement', models.CharField(blank=True, max_length=200)),
                ('eleve_payment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scuelo.eleve')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
