# Generated by Django 4.2.11 on 2024-05-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0002_alter_classe_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='hand',
            field=models.CharField(choices=[('', ''), ('DA', 'DA'), ('DM', 'DM'), ('DL', 'DL'), ('DV', 'DV')], default='', max_length=2),
        ),
    ]
