# Generated by Django 5.0.6 on 2024-05-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0002_alter_paiement_options_anneescolaire_nom_bref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='cs_py',
            field=models.CharField(choices=[('C', 'CS'), ('E', 'EXTRA'), ('P', 'PY'), ('A', 'ACC'), ('B', 'BRAVO')], max_length=7),
        ),
    ]
