# Generated by Django 4.2.13 on 2024-05-22 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0002_alter_eleve_parent_alter_eleve_tel_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='date_inscription',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='cs_py',
            field=models.CharField(choices=[('C', 'CS'), ('E', 'EXTRA'), ('P', 'PY'), ('A', 'ACC'), ('B', 'BRAVO')], default='C', max_length=7),
        ),
    ]
