# Generated by Django 4.2.11 on 2024-05-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuelo', '0003_alter_eleve_hand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='hand',
            field=models.CharField(blank=True, choices=[('', ''), ('DA', 'DA'), ('DM', 'DM'), ('DL', 'DL'), ('DV', 'DV')], default='', max_length=2),
        ),
    ]
